#!/bin/bash

set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo 'Specify the minecraft version, the nick and the profile, eg. "1.13.2 nick [profile]" or "1.12.2-forge nick [profile]"'
    echo 'The third optional argument specifies a folder for storing that version. This allows two forge installs of the same version, but different mods'
    exit 0
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )" # folder where all logs and supporting files are kept. Defaults to the same folder this script is in
cd "$DIR"

# setting these specific variables so they can be used inside GAME_ARGS sourced from $version_name.config
version_name=$1
auth_player_name=$2
game_profile="profiles/$auth_player_name-${3:-base}-$version_name"

mkdir -p "$game_profile"
game_directory="../../$game_profile"

if [[ ! -f versions/$version_name/$version_name.config ]]; then
    if [[ $version_name == *-forge ]]; then
        ./get-forge-client.sh ${version_name%%-forge}
    else
        ./get-minecraft-client.sh $version_name
    fi
    if [[ ! -f versions/$version_name/$version_name.config ]]; then
        echo "Download failed."
        exit 1
    fi
fi

cd versions/$version_name/
. $version_name.config

# https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
RAM_ALLOC_MIN="5000M" # 5G
RAM_ALLOC_MAX="5000M" # 5G, 10G
export JVM_OPTS="$JVM_OPTS -Xms${RAM_ALLOC_MIN} -Xmx${RAM_ALLOC_MAX} -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"

exec $JAVA $JVM_OPTS $MAIN $GAME_ARGS
